### ISSUE TITLE
A Problem Abot PortalThree

### ISSUE THREAD

**Issue by ChewieCodes** [Kami147/MinecraftSessionStealer#2]
Hi Kami147,

Recently one of your users of this session stealer has been using this for malicious purposes.

PortalThree has made a mod that has the stealer in it.

It has got the attention of the staff in hypixel : https://hypixel.net/threads/skyblock-modification-announcement-justenoughdungeons-jed.3663587/

This was the mod on github https://github.com/portalthree/JustEnoughDungeons

Could you take some action?

thx chewii

**Comment by thumperfuzzy** [comment]
As this is an issue with a specific person using it against how the author intended, and not the code itself, how is it the responsibility of the original author to take some action?

**Comment by Kami147** [comment]
Do you have another platform I can contact you on? For example discord?

**Comment by thumperfuzzy** [comment]
Sorry for the late reply, but I am on discord thumperfuzzy#5780 if you would like to contact me.
