### ISSUE TITLE
How do you login with the id if you already have it?

### ISSUE THREAD

**Issue by ExplicitPotato** [Kami147/MinecraftSessionStealer#3]
Title. I'm trying to get my account back as it got hacked, but I still have the logs and most recent session id of the hacker, as I know them personally.

**Comment by Kami147** [comment]
> Title. I'm trying to get my account back as it got hacked, but I still have the logs and most recent session id of the hacker, as I know them personally.

Session ID changes if the password is changed, I also don't think there's a public method to login to sessions with the new launcher

**Comment by Sqorx** [comment]
Can i get your Discord Kami?

**Comment by Kami147** [comment]
Kami#1337
