### ISSUE TITLE
Having issues

### ISSUE THREAD

**Issue by vaz3yy** [Kami147/MinecraftSessionStealer#4]
I edited the code and put my server webhook in the one spot where it said to. I converted it into a .jar and put it into my mods folder and nothing showed up in my dsicord. What am I doing wrong? Thanks in advance.

**Comment by Kami147** [comment]
it isn't designed for minecraft mods, to integrate it with minecraft you will need to add it to a forge sdk and call it from the main class

**Comment by vaz3yy** [comment]
Thank you, I got it working, do you know if there is currently anyway to log in with a session token?

**Comment by Kami147** [comment]
There is a method of login but it's not gone public yet
